services:
  nexus:
    image: sonatype/nexus3
    container_name: nexus
    ports:
      - "${NEXUS_PORT:-8081}:8081"
    volumes:
      - "${NEXUS_VOLUME:-./infra/nexus/data}:/nexus-data"
    restart: unless-stopped
    networks:
      - shared_net
  publisher:
    build:
      context: ./person-service/person-service-client
      dockerfile: Dockerfile
    depends_on:
      - nexus
  #    args:
  #      - NEXUS_URL=http://host.docker.internal:8081/repository/maven-snapshots/
  #      - NEXUS_USERNAME=admin
  #      - NEXUS_PASSWORD=3717grom

  postgres_keycloak:
    image: postgres:15
    container_name: postgres_keycloak
    env_file:
      - .env.individuals
    environment:
      POSTGRES_DB: ${KEYCLOAK_POSTGRES_DB}
      POSTGRES_USER: ${KEYCLOAK_POSTGRES_USER}
      POSTGRES_PASSWORD: ${KEYCLOAK_POSTGRES_PASSWORD}
    ports:
      - "${KEYCLOAK_POSTGRES_PORT}:5432"
    volumes:
      - postgres_keycloak_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-d", "${KEYCLOAK_POSTGRES_DB}", "-U", "${KEYCLOAK_POSTGRES_USER}" ]
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      - keycloak_net

  keycloak:
    image: quay.io/keycloak/keycloak:26.2
    container_name: keycloak
    command:
      - start-dev
      - --http-enabled=true
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres_keycloak
      KC_DB_URL_DATABASE: ${KEYCLOAK_POSTGRES_DB}
      KC_DB_USERNAME: ${KEYCLOAK_POSTGRES_USER}
      KC_DB_PASSWORD: ${KEYCLOAK_POSTGRES_PASSWORD}
      KC_HOSTNAME: localhost
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN_USER}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_METRICS_ENABLED: ${KEYCLOAK_METRICS_ENABLED}
      KC_HEALTH_ENABLED: ${KEYCLOAK_HEALTH_ENABLED}
      KC_HTTP_MANAGEMENT_PORT: ${KEYCLOAK_MANAGEMENT_PORT}
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HTTP_ENABLED: true
    ports:
      - "${KEYCLOAK_PORT}:8080"
      - "${KEYCLOAK_MANAGEMENT_PORT}:7800"
    depends_on:
      postgres_keycloak:
        condition: service_healthy
    networks:
      - keycloak_net

  individuals-api:
    image: individuals-api
    container_name: individuals-api
    env_file:
      - .env.individuals
    build:
      context: ./individuals-api
      dockerfile: Dockerfile
      args:
        - NEXUS_URL=${NEXUS_URL}
        - NEXUS_USERNAME=${NEXUS_USERNAME}
        - NEXUS_PASSWORD=${NEXUS_PASSWORD}
    environment:
      NEXUS_URL: ${NEXUS_URL}
      NEXUS_USERNAME: ${NEXUS_USERNAME}
      NEXUS_PASSWORD: ${NEXUS_PASSWORD}
    ports:
      - "${INDIVIDUALS_APP_PORT}:8092"
      - "${INDIVIDUALS_APP_DEBUG_PORT}:5005"
    depends_on:
      - keycloak
      - nexus
    networks:
      - keycloak_net
      - shared_net

  postgres-person:
    image: postgres:15
    container_name: postgres-person
    environment:
      POSTGRES_HOST: ${PERSON_POSTGRES_HOST}
      POSTGRES_DB: ${PERSON_POSTGRES_DB}
      POSTGRES_USER: ${PERSON_POSTGRES_USER}
      POSTGRES_PASSWORD: ${PERSON_POSTGRES_PASSWORD}
    ports:
      - "${PERSON_POSTGRES_PORT}:5432"
    volumes:
      - postgres_person_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-d", "${PERSON_POSTGRES_DB}", "-U", "${PERSON_POSTGRES_USER}" ]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s
    networks:
      - person_net

  person-service:
    build:
      context: ./person-service
      dockerfile: Dockerfile
      args:
        - NEXUS_URL=${NEXUS_URL}
        - NEXUS_USERNAME=${NEXUS_USERNAME}
        - NEXUS_PASSWORD=${NEXUS_PASSWORD}
    container_name: person-service
    env_file:
      - .env.person-service
    ports:
      - "${PERSON_APP_PORT}:${PERSON_APP_PORT}"
      - "${PERSON_APP_DEBUG_PORT}:${PERSON_APP_DEBUG_PORT}"
    depends_on:
      - postgres-person
      - nexus
    networks:
      - person_net
      - shared_net

  transaction-db:
    image: postgres:15
    container_name: postgres_transaction
    environment:
      POSTGRES_HOST: ${TRANSACTION_SERVICE_POSTGRES_HOST}
      POSTGRES_DB: ${TRANSACTION_SERVICE_POSTGRES_DB}
      POSTGRES_USER: ${TRANSACTION_SERVICE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${TRANSACTION_SERVICE_POSTGRES_PASSWORD}
    ports:
      - "${TRANSACTION_SERVICE_POSTGRES_PORT}:5432"
    volumes:
      - postgres_transaction_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-d", "${TRANSACTION_SERVICE_POSTGRES_DB}", "-U", "${TRANSACTION_SERVICE_POSTGRES_USER}" ]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s
    networks:
      - transaction_net

  transaction-service:
    build:
      context: ./transaction-service
      dockerfile: Dockerfile
      args:
        - NEXUS_URL=${NEXUS_URL}
        - NEXUS_USERNAME=${NEXUS_USERNAME}
        - NEXUS_PASSWORD=${NEXUS_PASSWORD}
    container_name: transaction-service
    env_file:
      - .env.transaction-service
    ports:
      - "${TRANSACTION_SERVICE_PORT}:${TRANSACTION_SERVICE_PORT}"
    depends_on:
      - postgres-person
      - nexus
    networks:
      - transaction_net

  prometheus:
    image: prom/prometheus:v3.4.2
    container_name: prometheus
    env_file:
      - .env
    ports:
      - "${PROMETHEUS_PORT}:${PROMETHEUS_PORT}"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - person_net

  grafana:
    image: grafana/grafana:12.0.2
    env_file:
      - .env
    container_name: grafana
    ports:
      - "${GRAFANA_PORT}:3000"
    restart: unless-stopped
    volumes:
      - ./monitoring/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    networks:
      - person_net

  jaeger:
    image: jaegertracing/jaeger:2.5.0
    env_file:
      - ./person-service/.env
    container_name: jaeger
    ports:
      - "4318:4318"
      - "4317:4317"
      - "6832:6832"
      - "5778:5778"
      - "16686:16686"
    restart: unless-stopped
    environment:
      OTEL_ENABLED: true
    networks:
      - person_net
      - shared_net


networks:
  keycloak_net:
  person_net:
  transaction_net:
  shared_net:
    external: true
volumes:
  postgres_person_data:
  postgres_keycloak_data:
  postgres_transaction_data:
  nexus-data: