INSERT INTO transaction_service.wallet_types (name,
                                              currency_code,
                                              status,
                                              archived_at,
                                              user_type,
                                              creator,
                                              modifier)
VALUES ('Default Wallet',
        'USD',
        'ACTIVE',
        NULL,
        'CUSTOMER',
        'system',
        'system'),
       ('Premium Wallet',
        'EUR',
        'ACTIVE',
        NULL,
        'CUSTOMER',
        'system',
        'system'),
       ('Corporate Wallet',
        'GBP',
        'INACTIVE',
        NULL,
        'BUSINESS',
        'system',
        'system');