buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath "org.flywaydb:flyway-gradle-plugin:${flywayVersion}"
        classpath "org.flywaydb:flyway-database-postgresql:${flywayVersion}"
        classpath "org.postgresql:postgresql:${postgreVersion}"
    }
}


plugins {
    id 'java'
    id 'org.springframework.boot' version "$springBootVersion"
    id 'io.spring.dependency-management' version "$springDependencyManagementVersion"
    id "org.flywaydb.flyway" version "$flywayVersion"
}

group = appGroup
version = appVersion

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenLocal()
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.flywaydb:flyway-core'
    implementation 'org.flywaydb:flyway-database-postgresql'
    implementation "org.springdoc:springdoc-openapi-starter-webmvc-ui:$springDocOpenApiVersion"
    // https://mvnrepository.com/artifact/org.hibernate.orm/hibernate-envers
    implementation 'org.springframework.data:spring-data-envers'
    implementation project(":person-service-client")


    implementation 'io.micrometer:micrometer-tracing-bridge-otel'
    implementation 'io.opentelemetry:opentelemetry-exporter-otlp'
//    implementation 'io.opentelemetry:opentelemetry-exporter-prometheus'
    runtimeOnly 'io.micrometer:micrometer-registry-prometheus'
    implementation "org.postgresql:postgresql:$postgreVersion"
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'



    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    // https://mvnrepository.com/artifact/org.mapstruct/mapstruct
    implementation("org.mapstruct:mapstruct:$mapstructVersion")
    // https://mvnrepository.com/artifact/org.mapstruct/mapstruct-processor
    annotationProcessor("org.mapstruct:mapstruct-processor:$mapstructVersion")

}

tasks.named('compileJava') {
}


tasks.named('test') {
    useJUnitPlatform()
}
