buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath "org.flywaydb:flyway-gradle-plugin:${flywayVersion}"
        classpath "org.flywaydb:flyway-database-postgresql:${flywayVersion}"
        classpath "org.postgresql:postgresql:${postgreVersion}"
    }
}


plugins {
    id 'java'
    id 'org.springframework.boot' version "$springBootVersion"
    id 'io.spring.dependency-management' version "$springDependencyManagementVersion"
    id "org.flywaydb.flyway" version "$flywayVersion"
}

group = appGroup
version = appVersion

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenLocal()
    mavenCentral()
    maven {
        url = uri("http://host.docker.internal:8081/repository/maven-releases/")
        credentials {
            username = project.findProperty("nexusUsername") ?: "admin"
            password = project.findProperty("nexusPassword") ?: "admin123"
        }
        // login and password
        allowInsecureProtocol = true
    }
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.flywaydb:flyway-core'
    implementation 'org.flywaydb:flyway-database-postgresql'
    implementation "org.springdoc:springdoc-openapi-starter-webmvc-ui:$springDocOpenApiVersion"
    implementation 'org.springframework.data:spring-data-envers'
    implementation "com.k3sh:person-service-client:$personServiceClientVersion"


    implementation 'io.micrometer:micrometer-tracing-bridge-otel'
    implementation 'io.opentelemetry:opentelemetry-exporter-otlp'
    runtimeOnly 'io.micrometer:micrometer-registry-prometheus'
    implementation "org.postgresql:postgresql:$postgreVersion"

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testImplementation("org.mockito:mockito-core:$mockitoVersion")
    testImplementation("org.junit.jupiter:junit-jupiter-api:$testJUnitVersion")
    testImplementation "org.testcontainers:testcontainers:$testcontainersVersion"
    testImplementation "org.testcontainers:junit-jupiter:$testJUnitJupiterTestContainerVersion"
    testImplementation "org.testcontainers:postgresql:$testcontainersPostgreVersion"
    testImplementation("com.fasterxml.jackson.core:jackson-databind:$jacksonDatabindVersion")


    implementation 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    implementation("org.mapstruct:mapstruct:$mapstructVersion")
    annotationProcessor("org.mapstruct:mapstruct-processor:$mapstructVersion")

}

tasks.named('compileJava') {
}


tasks.named('test') {
    useJUnitPlatform()
}
