buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath "org.flywaydb:flyway-gradle-plugin:${flywayVersion}"
        classpath "org.flywaydb:flyway-database-postgresql:${flywayVersion}"
        classpath "org.postgresql:postgresql:${postgreVersion}"
    }
}

plugins {
    id 'java'
    id 'org.springframework.boot' version "$springBootVersion"
    id 'io.spring.dependency-management' version "$springDependencyManagementVersion"
    id "org.flywaydb.flyway" version "$flywayVersion"
    id "org.openapi.generator" version "$openApiGeneratorVersion"
}

openApiGenerate {
    generatorName = "spring"
    inputSpec = "$projectDir/../openapi/openapi.yaml"
    apiPackage = "com.k3sh.person.api"
    modelPackage = "com.k3sh.common.model"
    configOptions = [
            "library"        : "spring-boot",
            "interfaceOnly"  : "true",
            "useSpringBoot3" : "true",
            "openApiNullable": "false"
    ]
    globalProperties = [
            "apis": ""
    ]
}

sourceSets {
    main {
        java {
            srcDirs = ["$projectDir/src/main/java", "$projectDir/build/generated/src/main/java", "$buildDir/generate-resources/main/src/main/java"]
        }
    }
}
group = appGroup
version = appVersion

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenLocal()
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.flywaydb:flyway-core'
    implementation 'org.flywaydb:flyway-database-postgresql'
    implementation "org.springdoc:springdoc-openapi-starter-webmvc-ui:$springDocOpenApiVersion"
    implementation "com.k3sh:common:$commonVersion"
    // https://mvnrepository.com/artifact/org.hibernate.orm/hibernate-envers
    implementation 'org.springframework.data:spring-data-envers'


    implementation 'io.micrometer:micrometer-tracing-bridge-otel'
    implementation 'io.opentelemetry:opentelemetry-exporter-otlp'
//    implementation 'io.opentelemetry:opentelemetry-exporter-prometheus'
    runtimeOnly 'io.micrometer:micrometer-registry-prometheus'
    implementation "org.postgresql:postgresql:$postgreVersion"
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'



    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    // https://mvnrepository.com/artifact/org.mapstruct/mapstruct
    implementation("org.mapstruct:mapstruct:$mapstructVersion")
    // https://mvnrepository.com/artifact/org.mapstruct/mapstruct-processor
    annotationProcessor("org.mapstruct:mapstruct-processor:$mapstructVersion")

}

tasks.named('compileJava') {
    dependsOn(tasks.openApiGenerate)
}

tasks.register('generateSchema', JavaExec) {
    group = "build"
    description = "Generates schema.sql from Hibernate mappings"
    classpath = sourceSets.main.runtimeClasspath
    mainClass.set("com.example.HibernateSchemaExporter")
}

tasks.named('test') {
    useJUnitPlatform()
}
