services:
  postgres:
    image: postgres:15
    container_name: postgres_person
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}" ]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s
    networks:
      - person_net

  person-service:
    build:
      context: .
      dockerfile: Dockerfile
      network: shared_net
    container_name: person-service
    ports:
      - "${APP_PORT}:${APP_PORT}"
      - "${APP_DEBUG_PORT}:${APP_DEBUG_PORT}"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
      APP_PORT: ${APP_PORT}
      APP_DEBUG_PORT: ${APP_DEBUG_PORT}
    depends_on:
      - postgres
    networks:
      - person_net
      - shared_net

  prometheus:
    image: prom/prometheus:v3.4.2
    container_name: prometheus
    ports:
      - "${PROMETHEUS_PORT}:${PROMETHEUS_PORT}"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - person_net

  grafana:
    image: grafana/grafana:12.0.2
    container_name: grafana
    ports:
      - "${GRAFANA_PORT}:3000"
    restart: unless-stopped
    volumes:
      - ./monitoring/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    networks:
      - person_net

  jaeger:
    image: jaegertracing/jaeger:2.5.0
    container_name: jaeger
    ports:
      - "4318:4318"
      - "4317:4317"
      - "6832:6832"
      - "5778:5778"
      - "16686:16686"
    restart: unless-stopped
    environment:
      OTEL_ENABLED: true
    networks:
      - person_net
      - shared_net


networks:
  person_net:
  shared_net:
    external: true
    name: shared_net
volumes:
  postgres_data:
  nexus-data: