appGroup=com.k3sh
appVersion=0.0.1
springBootVersion=3.5.3
springDependencyManagementVersion=1.1.7
postgreVersion=42.7.7
flywayVersion=11.9.1
openApiGeneratorVersion=7.14.0
commonVersion=1.0.0
springDocOpenApiVersion=2.2.0
mapstructVersion=1.6.3
mockitoVersion=5.18.0
testcontainersVersion=1.21.1
testcontainersPostgreVersion=1.20.0
testJUnitJupiterTestContainerVersion=1.21.1
