plugins {
    id("java")
    id 'org.openapi.generator' version "$openApiGeneratorVersion"
    id 'maven-publish'
}


group = "com.k3sh"
version = "1.0.0"

openApiGenerate {
    generatorName = "spring"
    inputSpec = "$projectDir/../../openapi/openapi.yaml"
    outputDir = "$buildDir/generated"
    modelPackage = "com.k3sh.common.model"
    apiPackage = "com.k3sh.common.api"
    generateApiDocumentation = false
    skipOperationExample = true
    generateModelTests = false
    generateModelDocumentation = false
    configOptions = [
            "library"             : "spring-boot",
            "interfaceOnly"       : "true",
            "useSpringBoot3"      : "true",
            "openApiNullable"     : "false",
            "skipDefaultInterface": "true",
            "skipDefaultExample"  : "true",
    ]
}

sourceSets.main.java.srcDir "$buildDir/generated/src/main/java"

compileJava.dependsOn tasks.openApiGenerate


publishing {
    publications {
        mavenJava(MavenPublication) {
            groupId = group
            artifactId = 'person-service-client'
            version = version

            from components.java
        }
    }

    repositories {
        maven {
            name = "LocalNexus"
            url = uri("http://localhost:8081/repository/maven-releases/")

            credentials {
                username = project.findProperty("nexusUsername") ?: "admin"
                password = project.findProperty("nexusPassword") ?: "admin123"
            }

            allowInsecureProtocol = true
        }
    }
}

repositories {
    mavenCentral()
}

dependencies {
    compileOnly "javax.annotation:javax.annotation-api:${javaxAnnotationApiVersion}"
    compileOnly "org.springframework:spring-core:${springCoreVersion}"
    compileOnly "jakarta.validation:jakarta.validation-api:${jakartaValidationApiVersion}"
    compileOnly "org.openapitools:jackson-databind-nullable:${jacksonDatabindNullableVersion}"
    compileOnly "io.swagger.core.v3:swagger-annotations:${swaggerAnnotationsVersion}"
    compileOnly "com.fasterxml.jackson.core:jackson-databind:${jacksonDatabindVersion}"
    compileOnly "jakarta.annotation:jakarta.annotation-api:${jakartaAnnotationApiVersion}"
    compileOnly 'org.springframework:spring-context:7.0.0-M6'
    implementation 'org.springframework:spring-web:7.0.0-M6'
    // https://mvnrepository.com/artifact/jakarta.servlet/jakarta.servlet-api
    compileOnly 'jakarta.servlet:jakarta.servlet-api:6.1.0'
}
