plugins {
    id 'java'
    id 'org.springframework.boot' version "${springBootVersion}"
    id 'io.spring.dependency-management' version "${springDependencyManagementVersion}"
    id "org.openapi.generator" version "$openApiGeneratorVersion"
}

version = project.property("version")

jar {
    manifest {
        attributes 'Main-Class': 'com.k3sh.bankapp.BankAppApplication'
    }
}

springBoot {
    buildInfo()
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
}

//openApiGenerate {
//    generatorName = "java"
//    inputSpec = "http://localhost:8092/v3/api-docs" // or use a URL
//    outputDir = "${layout.buildDirectory}/generated"
//    apiPackage = "com.k3sh.client.api"
//    modelPackage = "com.k3sh.client.model"
//    invokerPackage = "com.k3sh.client.invoker"
//    library = "feign"
//    configOptions = [
//            dateLibrary: "java8",
//            useFeignClientUrl: "true"
//    ]
//}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-webflux'
    implementation 'org.springframework.boot:spring-boot-starter-oauth2-resource-server'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation "ch.qos.logback.contrib:logback-json-classic:$logbackVersion"
    implementation "ch.qos.logback.contrib:logback-jackson:$logbackVersion"
    implementation "org.springdoc:springdoc-openapi-starter-webmvc-ui:$springOpenApiVersion"
    implementation("org.springframework.cloud:spring-cloud-starter-openfeign:$feignClientVersion")
    implementation "com.k3sh:common:${commonVersion}"

    implementation "io.github.openfeign:feign-micrometer:$feignMicrometerVersion"
    implementation 'io.micrometer:micrometer-tracing-bridge-otel'
    implementation 'io.opentelemetry:opentelemetry-exporter-otlp'

    implementation 'org.springframework.boot:spring-boot-starter-web'

    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'


    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'io.projectreactor:reactor-test'
    testImplementation 'org.springframework.security:spring-security-test'

    testImplementation "org.junit.jupiter:junit-jupiter:5.8.1"
    testImplementation "org.testcontainers:junit-jupiter:1.21.1"
    testImplementation "org.testcontainers:testcontainers:${testcontainersVersion}"



    testImplementation "com.github.dasniko:testcontainers-keycloak:$testcontainersKeycloakVersion"
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
    useJUnitPlatform()
}
