services:
  postgres:
    image: postgres:15
    container_name: keycloak_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}" ]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s
    networks:
      - keycloak_net

  keycloak:
    image: quay.io/keycloak/keycloak:26.2
    container_name: keycloak
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: ${POSTGRES_DB}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KC_HOSTNAME: localhost
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_METRICS_ENABLED: ${KEYCLOAK_METRICS_ENABLED}
      KC_HEALTH_ENABLED: ${KEYCLOAK_HEALTH_ENABLED}
      KC_HTTP_MANAGEMENT_PORT: ${KEYCLOAK_MANAGEMENT_PORT}
    ports:
      - "${KEYCLOAK_PORT}:8080"
      - "${KEYCLOAK_MANAGEMENT_PORT}:7800"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - keycloak_net

  individuals-api:
    image: individuals-api
    container_name: individuals-api
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${BANK_APP_PORT}:8092"
      - "${BANK_APP_DEBUG_PORT}:5005"
    depends_on:
      - keycloak
    networks:
      - keycloak_net
      - shared_net

networks:
  keycloak_net:
  shared_net:
    external: true
volumes:
  postgres_data: