version=1.0.0
appGroup=com.k3sh

springBootVersion=3.5.0
springDependencyManagementVersion=1.1.7

logbackVersion = 0.1.5

springOpenApiVersion=2.8.8
testcontainersKeycloakVersion=3.7.0
testcontainersVersion=1.21.1
testJUnitVersion=5.13.1
testJUnitJupiterVersion=5.13.3
testJUnitJupiterTestContainerVersion=1.21.1

openApiGeneratorVersion=7.14.0
feignClientVersion=4.3.0
feignMicrometerVersion=13.6

personServiceClientVersion=1.0.0