name: BankApp monorepo
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
env:
  GPR_REPO_URL: "https://maven.pkg.github.com/gromikkool/bank-app"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Make all gradlew scripts executable
        run: find . -name "gradlew" -exec chmod +x {} +

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'corretto'
          cache: 'gradle'

      # Step 1: Publish Service B (The dependency)

      - name: Publish person-service-client
        run: cd person-service/person-service-client && ./gradlew publish -PrepoUrl=${{ env.GPR_REPO_URL }} -PgprUser=${{ secrets.GPR_USER }} -PgprKey=${{ secrets.GITHUB_TOKEN }}

      - name: Publish transaction-service-client
        run: cd transaction-service/transaction-service-client && ./gradlew publish -PrepoUrl=${{ env.GPR_REPO_URL }} -PgprUser=${{ secrets.GPR_USER }} -PgprKey=${{ secrets.GITHUB_TOKEN }}

      - name: Build service individuals-API
        run: cd individuals-api && ./gradlew build -x test -PrepoUrl=${{ env.GPR_REPO_URL }} -PgprUser=${{ secrets.GPR_USER }} -PgprKey=${{ secrets.GITHUB_TOKEN }}

      - name: Build service transaction-service
        run: cd transaction-service && ./gradlew build -x test -PrepoUrl=${{ env.GPR_REPO_URL }} -PgprUser=${{ secrets.GPR_USER }} -PgprKey=${{ secrets.GITHUB_TOKEN }}

      - name: Build service person-service
        run: cd person-service && ./gradlew build -x test -PrepoUrl=${{ env.GPR_REPO_URL }} -PgprUser=${{ secrets.GPR_USER }} -PgprKey=${{ secrets.GITHUB_TOKEN }}


